### ISSUE TITLE
Collection conversion seems broken

### ISSUE THREAD

**Issue by fbiville** [x-stream/xstream#10] opened 2015-06-04 14:54 UTC
The implementation of [`canConvert`](https://github.com/x-stream/xstream/blob/master/xstream/src/java/com/thoughtworks/xstream/converters/collections/CollectionConverter.java#L67) seems very dubious.
We ran into a production issue where a Guava `ImmutableList` got converted into an array of arrays instead of a simple array.

Why not, at the very least, replace hardcoded list implementations with `List.class.isAssignableFrom(type)`?

**Comment by fbiville** [comment] 2015-06-04 15:00
Here is a fix from a forked project (https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/util/xstream/ImmutableListConverter.java).

Not saying this is the way to go, but it can be helpful.

**Comment by joehni** [comment] 2015-06-18 19:16
This is  aduplicate of [XSTR-557](http://x-stream.github.io/jira/557). The behavior is by design though. XStream would silently ignore additional memberf of a derived collection using isAssignableFrom in canConvert.

However, the proper way to support ImmutableList in XStream would be:

    xstream.registerConverter(
        new CollectionConverter(xstream.getMapper(), ImmutableList.class));

**Closed by joehni** 2015-06-18 19:16 UTC
Labels: duplicate, wontfix
