### ISSUE TITLE
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields 

### ISSUE THREAD

**Issue by joelparkerhenderson** [x-stream/xstream#172] opened 2019-10-29 21:29 UTC
This warning happens upon new download and run of OptaPlanner, which is a free open source constraint solver. What is the recommend treatment please? 

```
Starting examples app with java from environment variable PATH...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/Users/joel/projects/optaplanner/binaries/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Replicate: 

1. Download OptaPlanner and unzip it.

2. Run the examples e.g. `examples/runExamples.sh`.

3. Choose any example  e.g. in the GUI, click "Traveling Salesman".

**Comment by joehni** [comment] 2019-11-03 15:43
Duplicate of #101. Ignore it for now.

**Closed by joehni** 2019-11-03 15:43 UTC
Labels: duplicate
