### ISSUE TITLE
Sometimes the high concurrency can lead to CPU 100%

### ISSUE THREAD

**Issue by springdawn2003** [x-stream/xstream#32] opened 2015-12-14 01:48 UTC
Sometimes the high concurrency can lead to CPU 100%.Proposed 'com.thoughtworks.xstream.core.util.PrioritizedList:private final Set set = new TreeSet();' to 'private final Set set = new ConcurrentSkipListSet();'.

**Comment by joehni** [comment] 2015-12-17 11:36
Can you give more information, how the situation occurs?

**Comment by springdawn2003** [comment] 2015-12-18 07:48
testing servers(jetty 9.2.13):

![image](https://cloud.githubusercontent.com/assets/937576/11891836/5de522ac-a59d-11e5-9570-ae4c3287203b.png)

test case : xstream.fromXML(xml);
up to 50  user on loadrunner,cpu will up to 100% and can't  down again.....

![xstream_problems_00](https://cloud.githubusercontent.com/assets/937576/11891756/86f445a2-a59c-11e5-9fe4-6eb170ad2fca.jpg)

use jmc trace the source:

![xstream_problems_01](https://cloud.githubusercontent.com/assets/937576/11891762/8e28b952-a59c-11e5-8a15-add9e9ee2723.jpg)

**Comment by joehni** [comment] 2015-12-18 11:19
Thanks for the detailed information. AFAICS it is a duplicate of #2. Therefore I close this issue and you may track the other one.

**Closed by joehni** 2015-12-18 11:19 UTC
Labels: duplicate
